Level 2
SizovSergey/movies-explorer-frontend pull request #1
Opened 2023-08-28 13:46 UTC by SizovSergey

Попытка сдать верстку

2023-08-28 15:03 UTC, Savallera requested changes
# Резюме по работе:

Здравствуйте!
У Вас получилась хорошая работа для первого раза. Будет еще 3 итерации для того, чтобы над ней можно было еще поработать и она выгодно смотрелась в Вашем портфолио.
Вносите правки без спешки, следите за тем, что изменилось после внесения той или иной правки в элементе. Убедитесь перед отправкой, что все правки внесены. Если есть трудности - обращайтесь к наставнику и старшему студенту, они обязательно Вам помогут.

## Верстка и JSX

### Критерии, влияющие на работоспособность
- [ ] <!--12--> Все блоки и элементы из макета сверстаны. Размеры и расположение не отличаются от макета на более, чем на 30px на десктопной версии и на 10px на остальных размерах экрана, для которых подготовлен макет. Отличия в размерах не должны визуально противоречить макету и выбиваться из заложенной в макет сетки, в этом случае требуется более строгое соответствие размерам макета.

- Кнопка Узнать больше в дефолтном состоянии не имеет прозрачность по макету (только границы)
- https://yadi.sk/d/hZWpgA0Zx6snVA цвет мобильного меню не по макету
- толщина шрифта 500 не подключена в проекте, рендерится bold, например, здесь текст сильно визуально отличается от макета https://yadi.sk/i/hpdppkoqBqHDnQ. Дальше на примере скорректируйте остальные отличия.
- https://yadi.sk/d/viCoV4nFp-1Z8Q При загрузке проекта пользователь авторизован, что не соотв. макету
- https://yadi.sk/i/pFobDXbDqzAXrw Поиск - Найти, отступы и размеры чекбокса

Главная
- 1280 https://yadi.sk/i/ng-RU8XkhhG0JQ https://yadi.sk/i/9_07_8J7utR40w https://yadi.sk/i/F8n_VAMMirS2Tw
- 768 https://yadi.sk/i/fRrR3OWX64U4EA высота строки и отступ, https://yadi.sk/i/bzIoomuV1FZDUg параметры текста и отступ, https://yadi.sk/i/W5UaY3o_PkfvfA отступ
- 320 https://yadi.sk/i/i0Zjn_R6lN1ULw https://yadi.sk/i/rsszSLx0EPfL3g https://yadi.sk/i/-iGnEzUXnPMjrw https://yadi.sk/i/yVGpeI-kKsQe-g https://yadi.sk/i/j0pu58DIlhciYg https://yadi.sk/i/o8BTnn3gxajWvg https://yadi.sk/i/KxDQagitQG39sg параметры текста и отступы

Фильмы/Сохраненные
- 1280 https://yadi.sk/i/N8BLDKSUeMh9_A отступы
- 320 https://yadi.sk/i/KJ2xGrhRo_IkDQ отступы и параметры текста, https://yadi.sk/i/qafGtrvVFGufDw отступ и ширина кнопки

- Все разрешения https://yadi.sk/d/6UYG3ddVLIJJAg https://yadi.sk/i/sNWPwZyUnz49Eg https://yadi.sk/i/X2aYTE6Oh08fug в Сохраненных отличный отступ до подвала
- 320 Меню https://yadi.sk/i/EeuL6UjqM1rddQ
- 320 Регистрация и Вход https://yadi.sk/d/cEvkuY9Qnu1kNw https://yadi.sk/d/DNm_q0tT-LxGUg отступы

- [ ] <!--10.55--> Проект адаптирован под различные разрешения экрана. Горизонтальный скролл не возникает на разрешениях от 320 пикселей и больше. Нельзя скрывать полосу прокрутки свойством overflow: hidden.

- https://yadi.sk/i/s14VrClYWaP73g https://yadi.sk/i/YwMcWywWrX7kww https://yadi.sk/d/GvHRahx8e-ZPGg Обратите внимание, что при сужении экрана образуется горизонтальный скролл. Это чаще всего происходит когда элементы не влезают по ширине, стоит проверить фиксированные ширины, размеры заголовков и перестройку сетки на брейкпоинтах, внести соотв. изменения. Помните также, что медиа запросы должны быть сгруппированы, не менее 150-200п разницей.

- [ ] <!--9.55--> Корректно работает навигация между страницами и ссылки на внешние ресурсы: ни одна ссылка не ведёт в пустоту или на якорь, внешние ссылки открываются в новой вкладке. На все страницы проекта можно попасть, а скрытые блоки можно отобразить.

- Узнать больше - пустая ссылка (можно сделать якорь вниз к секциям)
- кнопка выйти из аккаунта на странице профиль может вести на главную или страницу входа

- [ ] <!--5.55--> Именование классов сделаны по БЭМ.

- Есть ошибки по БЭМ, https://yadi.sk/i/nQGL3kHq-wV8TQ https://yadi.sk/i/JXYS4yg2Qr2bhA. Вам следует самостоятельно на примере найти и исправить все похожие случаи. Проверить правильность наименования классов можно также тут: https://nglazov.github.io/bem-validator-page/
- about-project__timeline-green, about-project__timeline-grey - здесь будет уместно использовать сложные модификаторы, чтобы уточнить колонку
- authTemplate__title - при именовании селекторов следует придерживаться единообразия, так в большинстве использован кебаб-кейс, auth-template__title (на примере скорректируйте все подобные случаи)

- [ ] <!--8.55--> Отзывчивая вёрстка, которая корректно тянется на всех промежуточных разрешениях.

- https://yadi.sk/i/JIZ5rnDdVYLAoQ на больших экранах проект тянется шире чем по самому большому макету 1280.
- https://yadi.sk/i/seme0Ejpbs7Few присутствует сильный вертикальный скролл на мобильных
- https://yadi.sk/d/qiygPfYj3O0C9A https://yadi.sk/d/4QMUqAgOJZ_qjw контент следует сделать отзывчивым на всех устройствах. Также обратите внимание, что на страницах 404, профиль, регистрация и вход в макете выравнивание по вертикали идет относительно высоты вьюпорта, это значит, что на любых других устройствах оно должно центрироваться без фиксации высоты по макету не образовывая вертикальный скролл. Для реализации можно использовать технологию построения через флекс/грид, когда контент центрируется, шапка прижата к верху, футер к низу. Можно лучше на главной сделать липкий футер прижав хедер и растянув основной контент [Как создать липкий футер с помощью flexbox](https://webformyself.com/kak-sozdat-lipkij-futer-s-pomoshhyu-flexbox/).
- https://yadi.sk/d/iujE_JKv5UOFmg https://yadi.sk/i/lPJKtsudVVTGRA В любом месте где есть контент не следует делать фиксацию по высоте, т.к. контент может измениться и это не должно поломать отображение. Если блок содержит фоновое изображение и контент используйте минимальную высоту, Вам следует самостоятельно на примере найти и исправить все похожие случаи

- [ ] <!--3.38--> В коде используется семантическая разметка: применяются семантические теги, выбор элементов при вёрстке корректен (параграф должен быть параграфом, список — списком); структура DOM-дерева состоит не только из контейнеров div.

- about-me__student можно использовать сем.заголовок, только следите за иерархией относительно секции
- authTemplate__title profile__title - каждой отдельной странице нужен заголовок 1 уровня
- footer__title - можно использовать сем.заголовок в каждой секции.
- header__button-login кнопка внутри ссфлки в данном случае выглядит перегружено, можно ссылки стилизовать как кнопку, использовать модификаторы.
- authTemplate__line movies-card__line profile__line хорошей практикой считается стилизовать декоративные линии не перегружая разметку
- из main следует вытянуть header и footer на каждой отдельной странице
- странице 404 не хватает main

- [x] <!--3.38--> Для позиционирования элементов выбран верный подход, описанный корректным синтаксисом.
- [x] <!--3.38--> Каркас макета реализован на Flex layout или Grid layout;
- [x] <!--3.38--> Инфраструктурные файлы проекта созданы через CRA.
- [ ] <!--3.38--> Работа модальных окон настроена.

- https://yadi.sk/d/1ilpnIli5txNcw Обратите внимание на страницу UI в макете Figma. На странице профиля следует использовать логику по макету. Изначально данные не доступны к изменению, после нажатия на Кнопку Редактировать состояние полей меняется, также нижняя панель с кнопками меняет свой вид. Также есть состояния ошибки (это можно заложить в верстку).
- https://yadi.sk/d/tjBi66NbbIiUUA при входе (валидно заполненных полях) отображаются ошибки

- [ ] Разметка портирована в JSX:
	- [x] <!--3.38--> разметка заключена в ( ), лишние пустые <div> для этого не используются;
	- [x] <!--3.38--> разметка вынесена в соответствующие ей компоненты.
- [ ] В проекте есть:
	- [x] <!--3.38--> директория images/ с картинками,
	- [x] <!--3.38--> директория components/ с JS и CSS-файлами компонентов,
	- [x] <!--3.38--> директория fonts/ со шрифтами.

### Хорошие практики
- [ ] <!--2.14--> Кнопки, инпуты и ссылки реализованы во всех состояниях, указанных в макете.

- https://yadi.sk/d/s6IbfQHkeSILKQ у кнопок нет ховер эффекта, также ссылка и стрелка это один элемент, можно стрелочку оформить на псевдоэлементе у ссылки, чтобы она также менялась при ховере и переходила [...]

2023-08-31 06:14 UTC, SizovSergey reviewed
Правки связанные с БЭМ

2023-08-31 07:01 UTC, Savallera requested changes
# Резюме по работе:

Здравствуйте!
Готово 2 ревью на Ваш проект. Много пунктов засчитано и проделана отличная работа по первому ревью! Уверена, что у Вас все получится.

## Верстка и JSX

### Критерии, влияющие на работоспособность
- [ ] <!--12--> Все блоки и элементы из макета сверстаны. Размеры и расположение не отличаются от макета на более, чем на 30px на десктопной версии и на 10px на остальных размерах экрана, для которых подготовлен макет. Отличия в размерах не должны визуально противоречить макету и выбиваться из заложенной в макет сетки, в этом случае требуется более строгое соответствие размерам макета.

- Кнопка Узнать больше в дефолтном состоянии не имеет прозрачность по макету (только границы)
- пропало мобильное меню и вкладки Фильмы/Сохраненные в хедере
- 768 https://yadi.sk/d/4oGZ6RJnG0Phsw Поиск

Главная
- 320 https://yadi.sk/d/1S9_VzFMuwqf7Q https://yadi.sk/d/vKgmickUsblHqw https://yadi.sk/d/-fxrUQnsY-x6Yg https://yadi.sk/d/ynzHFeCypiyZvw https://yadi.sk/d/J_-Q749wg1njnQ

- Все разрешения https://yadi.sk/d/iSIFLLcpckyFtg в Сохраненных отличный отступ до подвала

- [ ] <!--10.55--> Проект адаптирован под различные разрешения экрана. Горизонтальный скролл не возникает на разрешениях от 320 пикселей и больше. Нельзя скрывать полосу прокрутки свойством overflow: hidden.

- https://yadi.sk/d/dy1SOHXkStXHcw https://yadi.sk/d/HCPg5ALKra774w Обратите внимание, что при сужении экрана образуется горизонтальный скролл. Это чаще всего происходит когда элементы не влезают по ширине, стоит проверить фиксированные ширины, размеры заголовков и перестройку сетки на брейкпоинтах, внести соотв. изменения. Помните также, что медиа запросы должны быть сгруппированы, не менее 150-200п разницей.

- [x] <!--9.55--> Корректно работает навигация между страницами и ссылки на внешние ресурсы: ни одна ссылка не ведёт в пустоту или на якорь, внешние ссылки открываются в новой вкладке. На все страницы проекта можно попасть, а скрытые блоки можно отобразить.
- [ ] <!--5.55--> Именование классов сделаны по БЭМ.

- Есть ошибки по БЭМ, https://yadi.sk/d/ZtrZ6P7eFTaVJw https://yadi.sk/d/9CeWeIdM_bNUyQ. Вам следует самостоятельно на примере найти и исправить все похожие случаи. Проверить правильность наименования классов можно также тут: https://nglazov.github.io/bem-validator-page/

- [ ] <!--8.55--> Отзывчивая вёрстка, которая корректно тянется на всех промежуточных разрешениях.

- https://yadi.sk/d/99cAL_wst7e5sA https://yadi.sk/d/IWetlGky59yMmQ по отзывчивости небольшое замечание. Панель не нужно отодвигать к низу страницы, можно сам контейнер центрировать как в макете, а если экран по высоте меньше, то авто отступ у панели с кнопкой поднимается к полям.

- [ ] <!--3.38--> В коде используется семантическая разметка: применяются семантические теги, выбор элементов при вёрстке корректен (параграф должен быть параграфом, список — списком); структура DOM-дерева состоит не только из контейнеров div.

- about-me__title - заголовки в секции следует сделать 2 уровня (на отдельной странице должен быть заголовок 1 уровня только один)
- profile__title - каждой отдельной странице нужен заголовок 1 уровня
- из main следует вытянуть header и footer на каждой отдельной странице

- [x] <!--3.38--> Для позиционирования элементов выбран верный подход, описанный корректным синтаксисом.
- [x] <!--3.38--> Каркас макета реализован на Flex layout или Grid layout;
- [x] <!--3.38--> Инфраструктурные файлы проекта созданы через CRA.
- [x] <!--3.38--> Работа модальных окон настроена.
- [ ] Разметка портирована в JSX:
	- [x] <!--3.38--> разметка заключена в ( ), лишние пустые <div> для этого не используются;
	- [x] <!--3.38--> разметка вынесена в соответствующие ей компоненты.
- [ ] В проекте есть:
	- [x] <!--3.38--> директория images/ с картинками,
	- [x] <!--3.38--> директория components/ с JS и CSS-файлами компонентов,
	- [x] <!--3.38--> директория fonts/ со шрифтами.

### Хорошие практики
- [x] <!--2.14--> Кнопки, инпуты и ссылки реализованы во всех состояниях, указанных в макете.
- [x] <!--2.14--> В макете есть одинаковые элементы. Для их оформления должен быть переиспользован один компонент.
- [x] <!--2.14--> Шрифты подключены через @font-face.
- [x] <!--2.14--> Иконки экспортированы в формате SVG.
- [x] <!--2.14--> Элементы формы должны выделяться, когда на них установлен фокус. Состояние фокуса, а также outline стилизованы в соответствии с макетом или на своё усмотрение.
- [x] <!--2.14--> У формы должны быть заданы плейсхолдеры, валидированы обязательные поля.
- [x] <!--2.14--> reset.css запрещен.

### Рекомендации
- [ ] <!--1.68--> Для каждого шрифта указаны альтернативные варианты из системных шрифтов.

- Не везде указаны альтернативные шрифты / profile, burger - можно объявить семейство шрифтов родительскому блоку, а у всех дочерних удалить.

- [x] <!--1.67--> Для изображений задан атрибут alt с подходящий значением.
- [x] <!--1.67--> Растровые и векторные изображения оптимизированы;

## Количество баллов: 58

## Доп. Комментарии:
- https://yadi.sk/d/_uy9nMizCxC1wA для того, чтобы при нажатии на слово состояние чекбокса менялось слово следует оформить label с атрибутом for
- при правильно заполненных полях на странице вход и регистрация можно переходить на страницу с фильмами и авторизованного пользователя (меню)
- фоновый цвет секциям можно сделать на всю ширину вьюпорта, чтобы не было белых полос по бокам, помогут контейнеры. Контент внутри центрируется по макс. ширине от макета

2023-09-01 12:52 UTC, SizovSergey commented
> Правки связанные с БЭМ

2023-09-01 15:55 UTC, Savallera approved these changes
# Резюме по работе:

Здравствуйте!
Готово 3 ревью по Вашей работе. Поздравляю Вас Ваш проект принимается. Желаю дальнейших успехов Вам во всех начинаниях.

## Верстка и JSX

### Критерии, влияющие на работоспособность
- [x] <!--12--> Все блоки и элементы из макета сверстаны. Размеры и расположение не отличаются от макета на более, чем на 30px на десктопной версии и на 10px на остальных размерах экрана, для которых подготовлен макет. Отличия в размерах не должны визуально противоречить макету и выбиваться из заложенной в макет сетки, в этом случае требуется более строгое соответствие размерам макета.
- [x] <!--10.55--> Проект адаптирован под различные разрешения экрана. Горизонтальный скролл не возникает на разрешениях от 320 пикселей и больше. Нельзя скрывать полосу прокрутки свойством overflow: hidden.
- [x] <!--9.55--> Корректно работает навигация между страницами и ссылки на внешние ресурсы: ни одна ссылка не ведёт в пустоту или на якорь, внешние ссылки открываются в новой вкладке. На все страницы проекта можно попасть, а скрытые блоки можно отобразить.
- [x] <!--5.55--> Именование классов сделаны по БЭМ.
- [x] <!--8.55--> Отзывчивая вёрстка, которая корректно тянется на всех промежуточных разрешениях.
- [x] <!--3.38--> В коде используется семантическая разметка: применяются семантические теги, выбор элементов при вёрстке корректен (параграф должен быть параграфом, список — списком); структура DOM-дерева состоит не только из контейнеров div.
- [x] <!--3.38--> Для позиционирования элементов выбран верный подход, описанный корректным синтаксисом.
- [x] <!--3.38--> Каркас макета реализован на Flex layout или Grid layout;
- [x] <!--3.38--> Инфраструктурные файлы проекта созданы через CRA.
- [x] <!--3.38--> Работа модальных окон настроена.
- [ ] Разметка портирована в JSX:
	- [x] <!--3.38--> разметка заключена в ( ), лишние пустые <div> для этого не используются;
	- [x] <!--3.38--> разметка вынесена в соответствующие ей компоненты.
- [ ] В проекте есть:
	- [x] <!--3.38--> директория images/ с картинками,
	- [x] <!--3.38--> директория components/ с JS и CSS-файлами компонентов,
	- [x] <!--3.38--> директория fonts/ со шрифтами.

### Хорошие практики
- [x] <!--2.14--> Кнопки, инпуты и ссылки реализованы во всех состояниях, указанных в макете.
- [x] <!--2.14--> В макете есть одинаковые элементы. Для их оформления должен быть переиспользован один компонент.
- [x] <!--2.14--> Шрифты подключены через @font-face.
- [x] <!--2.14--> Иконки экспортированы в формате SVG.
- [x] <!--2.14--> Элементы формы должны выделяться, когда на них установлен фокус. Состояние фокуса, а также outline стилизованы в соответствии с макетом или на своё усмотрение.
- [x] <!--2.14--> У формы должны быть заданы плейсхолдеры, валидированы обязательные поля.
- [x] <!--2.14--> reset.css запрещен.

### Рекомендации
- [x] <!--1.68--> Для каждого шрифта указаны альтернативные варианты из системных шрифтов.
- [x] <!--1.67--> Для изображений задан атрибут alt с подходящий значением.
- [x] <!--1.67--> Растровые и векторные изображения оптимизированы;

## Количество баллов: 100

## Доп. Комментарии:
- https://yadi.sk/d/Pb71zz7VrVIweQ еще немножечко скорректируйте
- about-me__title - на главной не может быть двух заголовков первого уровня
- Меню - burger__menu-link-active обратите внимание, что подчеркивание только под контентом, можно элементу сделать ширину - max-content, также выравнивание по центру помогает.

2023-09-01 16:08 UTC, merged

2023-09-01 16:09 UTC, SizovSergey commented
Огромное спасибо за оценку этой работы.Ваше ревью было очень полезным для меня.